### ISSUE TITLE
Crash when render tasklist as pandoc

### ISSUE THREAD

**Issue by black-desk** [jgm/djot.js#71]
```djot
- [ ] a
```
```bash
djot ./example.dj -t pandoc
```
```
❯ git rev-parse HEAD
8975a421e844055c87a45d7f544267986d9aadef
❯ cat example.dj
- [ ] a
❯ ./djot ./example.dj -t pandoc
Error: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at PandocRenderer.addToPandocElts (/tmp/djot.js/lib/pandoc.js:138:44)
    at /tmp/djot.js/lib/pandoc.js:68:22
    at Array.forEach (<anonymous>)
    at PandocRenderer.toPandocChildren (/tmp/djot.js/lib/pandoc.js:67:27)
    at PandocRenderer.toPandoc (/tmp/djot.js/lib/pandoc.js:391:26)
    at toPandoc (/tmp/djot.js/lib/pandoc.js:884:40)
    at Object.<anonymous> (/tmp/djot.js/lib/cli.js:212:75)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)%
```

task_list has no `style`

**Comment by jgm** [comment]
Do you want to make a PR with a fix?

**Comment by black-desk** [comment]
I have no idea how should we fix this problem now. :(
