### ISSUE TITLE
No renderer for span when rendering as djot

### ISSUE THREAD

**Issue by bpj** [jgm/djot.js#79]
I get the following error when rendering a document which contains a span to djot.

Rendering the same to pandoc, html or ast works flawlessly.

The context is a filter which returns a span, in case that matters.

I installed latest with npm. The problem persists.

``` text
Error: Error: No renderer defined for node type span
Error: No renderer defined for node type span
    at DjotRenderer.renderNode (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:635:20)
    at DjotRenderer.renderChildren (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:615:18)
    at para (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:169:22)
    at DjotRenderer.renderNode (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:629:13)
    at DjotRenderer.renderChildren (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:615:18)
    at doc (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:130:22)
    at DjotRenderer.renderNode (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:629:13)
    at DjotRenderer.render (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:680:14)
    at renderDjot (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/djot-renderer.js:685:43)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/@djot/djot/lib/cli.js:202:70)
```

The ast output looks like this:

``` json
{
  "tag": "doc",
  "references": {},
  "footnotes": {},
  "children": [
    {
      "tag": "para",
      "children": [
        {
          "tag": "span",
          "children": [
            {
              "tag": "str",
              "text": "🆎"
            }
          ],
          "attributes": {
            "class": "emoji",
            "emoji": "ab"
          }
        },
        {
          "tag": "str",
          "text": " "
        },
        {
          "tag": "span",
          "children": [
            {
              "tag": "str",
              "text": "😠"
            }
          ],
          "attributes": {
            "class": "emoji",
            "emoji": "angry"
          }
        }
      ]
    }
  ]
}
```

**Comment by bpj** [comment]
Will there be a new release soon?
